name: fitnesstracker
services:
  db: 
    image: mysql:8.0.38
    container_name: ft-mysql
    hostname: db
    ports:
      # Use a port different to the default so we don't have to stop any running MySQL databases
      - 3310:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # Use a persistent data directory
      - ./db/data:/var/lib/mysql
    env_file:
      - './.env'
    environment:
      MYSQL_DATABASE: ft

  migrations:
    image: redgate/flyway:10.15.2-alpine
    container_name: migrations
    command: 'migrate && tail -f'
    env_file:
      - './.env'
    volumes:
      - ./db/flyway.conf:/flyway/conf/flyway.conf
      - ./db/migrations:/flyway/sql
  