/*
 * This file is generated by jOOQ.
 */
package com.dmoffat.fitnesstracker.db;


import com.dmoffat.fitnesstracker.db.tables.BodyWeight;
import com.dmoffat.fitnesstracker.db.tables.Exercise;
import com.dmoffat.fitnesstracker.db.tables.User;
import com.dmoffat.fitnesstracker.db.tables.Workout;
import com.dmoffat.fitnesstracker.db.tables.WorkoutExercise;
import com.dmoffat.fitnesstracker.db.tables.records.BodyWeightRecord;
import com.dmoffat.fitnesstracker.db.tables.records.ExerciseRecord;
import com.dmoffat.fitnesstracker.db.tables.records.UserRecord;
import com.dmoffat.fitnesstracker.db.tables.records.WorkoutExerciseRecord;
import com.dmoffat.fitnesstracker.db.tables.records.WorkoutRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in ft.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BodyWeightRecord> KEY_BODY_WEIGHT_PRIMARY = Internal.createUniqueKey(BodyWeight.BODY_WEIGHT, DSL.name("KEY_body_weight_PRIMARY"), new TableField[] { BodyWeight.BODY_WEIGHT.ID }, true);
    public static final UniqueKey<ExerciseRecord> KEY_EXERCISE_PRIMARY = Internal.createUniqueKey(Exercise.EXERCISE, DSL.name("KEY_exercise_PRIMARY"), new TableField[] { Exercise.EXERCISE.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_EMAIL = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_email"), new TableField[] { User.USER.EMAIL }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<WorkoutRecord> KEY_WORKOUT_PRIMARY = Internal.createUniqueKey(Workout.WORKOUT, DSL.name("KEY_workout_PRIMARY"), new TableField[] { Workout.WORKOUT.ID }, true);
    public static final UniqueKey<WorkoutExerciseRecord> KEY_WORKOUT_EXERCISE_PRIMARY = Internal.createUniqueKey(WorkoutExercise.WORKOUT_EXERCISE, DSL.name("KEY_workout_exercise_PRIMARY"), new TableField[] { WorkoutExercise.WORKOUT_EXERCISE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BodyWeightRecord, UserRecord> BODY_WEIGHT_USER_ID_FK = Internal.createForeignKey(BodyWeight.BODY_WEIGHT, DSL.name("body_weight_user_id_fk"), new TableField[] { BodyWeight.BODY_WEIGHT.USER_ID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true);
    public static final ForeignKey<WorkoutRecord, UserRecord> WORKOUT_USER_ID_FK = Internal.createForeignKey(Workout.WORKOUT, DSL.name("workout_user_id_fk"), new TableField[] { Workout.WORKOUT.USER_ID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true);
    public static final ForeignKey<WorkoutExerciseRecord, ExerciseRecord> EXERCISE_ID_FK = Internal.createForeignKey(WorkoutExercise.WORKOUT_EXERCISE, DSL.name("exercise_id_fk"), new TableField[] { WorkoutExercise.WORKOUT_EXERCISE.EXERCISE_ID }, Keys.KEY_EXERCISE_PRIMARY, new TableField[] { Exercise.EXERCISE.ID }, true);
    public static final ForeignKey<WorkoutExerciseRecord, WorkoutRecord> WORKOUT_ID_FK = Internal.createForeignKey(WorkoutExercise.WORKOUT_EXERCISE, DSL.name("workout_id_fk"), new TableField[] { WorkoutExercise.WORKOUT_EXERCISE.WORKOUT_ID }, Keys.KEY_WORKOUT_PRIMARY, new TableField[] { Workout.WORKOUT.ID }, true);
}
