/*
 * This file is generated by jOOQ.
 */
package com.dmoffat.fitnesstracker.db;


import com.dmoffat.fitnesstracker.db.tables.BodyWeight;
import com.dmoffat.fitnesstracker.db.tables.Exercise;
import com.dmoffat.fitnesstracker.db.tables.SpringSession;
import com.dmoffat.fitnesstracker.db.tables.SpringSessionAttributes;
import com.dmoffat.fitnesstracker.db.tables.User;
import com.dmoffat.fitnesstracker.db.tables.Workout;
import com.dmoffat.fitnesstracker.db.tables.WorkoutExercise;


/**
 * Convenience access to all tables in ft.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ft.body_weight</code>.
     */
    public static final BodyWeight BODY_WEIGHT = BodyWeight.BODY_WEIGHT;

    /**
     * The table <code>ft.exercise</code>.
     */
    public static final Exercise EXERCISE = Exercise.EXERCISE;

    /**
     * The table <code>ft.SPRING_SESSION</code>.
     */
    public static final SpringSession SPRING_SESSION = SpringSession.SPRING_SESSION;

    /**
     * The table <code>ft.SPRING_SESSION_ATTRIBUTES</code>.
     */
    public static final SpringSessionAttributes SPRING_SESSION_ATTRIBUTES = SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES;

    /**
     * The table <code>ft.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>ft.workout</code>.
     */
    public static final Workout WORKOUT = Workout.WORKOUT;

    /**
     * The table <code>ft.workout_exercise</code>.
     */
    public static final WorkoutExercise WORKOUT_EXERCISE = WorkoutExercise.WORKOUT_EXERCISE;
}
