/*
 * This file is generated by jOOQ.
 */
package com.dmoffat.fitnesstracker.db.tables.records;


import com.dmoffat.fitnesstracker.db.tables.BodyWeight;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BodyWeightRecord extends UpdatableRecordImpl<BodyWeightRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ft.body_weight.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ft.body_weight.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ft.body_weight.user_id</code>.
     */
    public void setUserId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>ft.body_weight.user_id</code>.
     */
    public UInteger getUserId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>ft.body_weight.logged_on</code>.
     */
    public void setLoggedOn(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>ft.body_weight.logged_on</code>.
     */
    public LocalDate getLoggedOn() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BodyWeightRecord
     */
    public BodyWeightRecord() {
        super(BodyWeight.BODY_WEIGHT);
    }

    /**
     * Create a detached, initialised BodyWeightRecord
     */
    public BodyWeightRecord(UInteger id, UInteger userId, LocalDate loggedOn) {
        super(BodyWeight.BODY_WEIGHT);

        setId(id);
        setUserId(userId);
        setLoggedOn(loggedOn);
        resetChangedOnNotNull();
    }
}
