/*
 * This file is generated by jOOQ.
 */
package com.dmoffat.fitnesstracker.db.tables.records;


import com.dmoffat.fitnesstracker.db.tables.SpringSessionAttributes;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpringSessionAttributesRecord extends UpdatableRecordImpl<SpringSessionAttributesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ft.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID</code>.
     */
    public void setSessionPrimaryId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID</code>.
     */
    public String getSessionPrimaryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME</code>.
     */
    public void setAttributeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_NAME</code>.
     */
    public String getAttributeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES</code>.
     */
    public void setAttributeBytes(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES</code>.
     */
    public byte[] getAttributeBytes() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpringSessionAttributesRecord
     */
    public SpringSessionAttributesRecord() {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES);
    }

    /**
     * Create a detached, initialised SpringSessionAttributesRecord
     */
    public SpringSessionAttributesRecord(String sessionPrimaryId, String attributeName, byte[] attributeBytes) {
        super(SpringSessionAttributes.SPRING_SESSION_ATTRIBUTES);

        setSessionPrimaryId(sessionPrimaryId);
        setAttributeName(attributeName);
        setAttributeBytes(attributeBytes);
        resetChangedOnNotNull();
    }
}
