/*
 * This file is generated by jOOQ.
 */
package com.dmoffat.fitnesstracker.db.tables.records;


import com.dmoffat.fitnesstracker.db.tables.SpringSession;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpringSessionRecord extends UpdatableRecordImpl<SpringSessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ft.SPRING_SESSION.PRIMARY_ID</code>.
     */
    public void setPrimaryId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION.PRIMARY_ID</code>.
     */
    public String getPrimaryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION.SESSION_ID</code>.
     */
    public void setSessionId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION.SESSION_ID</code>.
     */
    public String getSessionId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION.CREATION_TIME</code>.
     */
    public void setCreationTime(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION.CREATION_TIME</code>.
     */
    public Long getCreationTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION.LAST_ACCESS_TIME</code>.
     */
    public void setLastAccessTime(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION.LAST_ACCESS_TIME</code>.
     */
    public Long getLastAccessTime() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION.MAX_INACTIVE_INTERVAL</code>.
     */
    public void setMaxInactiveInterval(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION.MAX_INACTIVE_INTERVAL</code>.
     */
    public Integer getMaxInactiveInterval() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION.EXPIRY_TIME</code>.
     */
    public void setExpiryTime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION.EXPIRY_TIME</code>.
     */
    public Long getExpiryTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>ft.SPRING_SESSION.PRINCIPAL_NAME</code>.
     */
    public void setPrincipalName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ft.SPRING_SESSION.PRINCIPAL_NAME</code>.
     */
    public String getPrincipalName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpringSessionRecord
     */
    public SpringSessionRecord() {
        super(SpringSession.SPRING_SESSION);
    }

    /**
     * Create a detached, initialised SpringSessionRecord
     */
    public SpringSessionRecord(String primaryId, String sessionId, Long creationTime, Long lastAccessTime, Integer maxInactiveInterval, Long expiryTime, String principalName) {
        super(SpringSession.SPRING_SESSION);

        setPrimaryId(primaryId);
        setSessionId(sessionId);
        setCreationTime(creationTime);
        setLastAccessTime(lastAccessTime);
        setMaxInactiveInterval(maxInactiveInterval);
        setExpiryTime(expiryTime);
        setPrincipalName(principalName);
        resetChangedOnNotNull();
    }
}
